# Generated by Django 5.1.4 on 2024-12-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_update_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='published_at',
            new_name='created_at',
        ),
    ]
